# Generated by Django 4.0.4 on 2022-05-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_excerpt_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
