# Generated by Django 4.0.4 on 2022-05-23 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
